# Generated by Django 4.0.4 on 2022-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
