# Generated by Django 4.0.4 on 2022-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(max_length=4, verbose_name='Дата релиза'),
        ),
    ]
