# Generated by Django 4.0.4 on 2022-04-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.CharField(default='Ссылки нет', max_length=500, verbose_name='Ссылка на альбом'),
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(default='На данный момент альбомы не были добавлены на сайт', related_name='albumsartist', to='music.album', verbose_name='Альбомы'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(related_name='membersartist', to='music.member', verbose_name='Участник'),
        ),
    ]
