# Generated by Django 4.0.4 on 2022-04-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All',
        ),
    ]
