# Generated by Django 4.0.4 on 2022-04-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
