# Generated by Django 4.0.4 on 2022-04-26 14:36

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media\x0e.jpg', null=True, upload_to=music.models.upload_profile_image, verbose_name='Аватар'),
        ),
    ]
