# Generated by Django 4.0.4 on 2022-04-26 14:39

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media\x0e.jpg', upload_to=music.models.upload_profile_image, verbose_name='Аватар'),
        ),
    ]
