# Generated by Django 4.0.4 on 2022-05-02 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0025_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=500, verbose_name='Ответ на комментарий')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('comment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='music.commentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answeruser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'блок ответов на комментарии',
                'verbose_name_plural': 'блок ответов на комментарии',
            },
        ),
    ]
