# Generated by Django 4.0.4 on 2022-05-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_alter_commentmodel_date_posted_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
