# Generated by Django 4.0.4 on 2022-05-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0028_commentmodel_parent_alter_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music.post', verbose_name='запись с постом'),
        ),
    ]
