# Generated by Django 4.0.4 on 2022-05-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_comment_reply_delete_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
